### ISSUE TITLE
Logs leaking credentials

### ISSUE THREAD

**Issue by OmgImAlexis** [daspanel/mailhog-mail-catcher#1]
Same issue as before but this is for the mail catcher.

The logs contain the username and password in plain text as it logs all messages coming into the container. This isn't just an issue with the daspanel password being shown but also anything being sent through the container.

It's also listing the MYSQL root password, daspanel api key, etc.

**Comment by admindaspanel** [comment]
@OmgImAlexis  Your are right, mail-catcher (mailhog) is loging in stdout every message received by it. I will try to solve this issue is next 3 days.

**Comment by admindaspanel** [comment]
Mailhog has no option to suppress log messages. To solve the problem I had to redirect all error messages and logs  to /dev/null.

You will need to update your images by running:

`docker pull daspanel/mailhog-mail-catcher`

**Comment by OmgImAlexis** [comment]
Looks good.
